version: '3'

services:

  elasticsearch:
    image: elasticsearch:7.11.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - 9200:9200
      - 9300:9300
    networks:
      - elasticnet
    volumes:
      - data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.11.2
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    ports: 
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elasticnet
  
networks:
  elasticnet:
    driver: bridge

volumes:
  data:
    driver: local